apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  # namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  # namespace: default
spec:
  selector:
    app: echo
  ports:
  - name: http
    port: 5678
    targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        # consul.hashicorp.com/connect-service: "echo"
    spec:
      serviceAccountName: echo
      containers:
      - name: echo
        image: hashicorp/http-echo:1.0
        args: ["-text=hello-from-dc2"]
        ports:
        - containerPort: 5678
